CREATE DATABASE IF NOT EXISTS guvi CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE guvi;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  dob DATE NOT NULL,
  contact VARCHAR(20) NOT NULL
);
